### ISSUE TITLE
Arcadia dumping incorrectly

### ISSUE THREAD

**Issue by PsychoFox11** [sanni/cartreader#1013]
### OSCR firmware version

14.0

### OSCR hardware version

HW5 Rev5

### System used

Emerson Arcadia 2001

### Describe the issue.

Only one cart has been tested so far, but I hope to get more, and see an issue on this one. There is only one BIT incorrect in the dump. My AtariMax Maxflash dumps it correctly, matching the very old hash on No-Intro. OSCR just records a single bit wrong.

Here's a diff with the problem shown in red. Maxflash/No-intro on top, OSCR on bottom. As I hope to do more, and it's a fairly neglected system, I'd love to see this fixed! Dump is of the game "Tanks a Lot".
I'm also fairly confident that a single bit error would not be caused by the adapter, and has to be software related.
<img width="560" alt="image" src="https://github.com/user-attachments/assets/ed4aa39a-8088-430c-8137-cf2e451864ee">

**Comment by sanni** [comment]
Try adding a few additional NOP; [here](https://github.com/sanni/cartreader/blob/master/Cart_Reader/ARC.ino#L131) and see if that changes anything.

**Comment by breyell** [comment]
> Try adding a few additional NOP; [here](https://github.com/sanni/cartreader/blob/master/Cart_Reader/ARC.ino#L131) and see if that changes anything.

Added a single NOP and that resolved the issue - thanks!

**Comment by PsychoFox11** [comment]
Nice! (Just noting I filed this based on Bonzo's dump as he's making my adapter and borrowed my cart). So should be good!

**Comment by PsyK0p4T** [comment]
added that to code :) Thanks !
