### ISSUE TITLE
setupCFI not declared in this scope

### ISSUE THREAD

**Issue by PsyK0p4T** [sanni/cartreader#1016]
### OSCR firmware version

14.3

### OSCR hardware version

HW5 Rev1

### System used

Game Boy (Color)

### Describe the issue.

I've tried to only enable ENABLE_FLASH + ENABLE_GBX, with ENABLE_SNES disabled.
Compiler displays various errors with setupCFI();

**Comment by sanni** [comment]
Good catch. 😃 
I found some more too.

**Comment by PsyK0p4T** [comment]
Fixed with your latest commits, thanks sanni !
