### ISSUE TITLE
Error 'navigateMenu' was not declared in this scope

### ISSUE THREAD

**Issue by PsyK0p4T** [sanni/cartreader#1022]
### OSCR firmware version

14.4

### OSCR hardware version

HW5 Rev1

### System used

Sega Mega Drive/Genesis

### Describe the issue.

When only "#define ENABLE_MD" module is enabled, compiling the sketch returns the following error

MD.ino: In function 'void force_cartSize_MD()':
MD:2907:14: error: 'navigateMenu' was not declared in this scope
   cartSize = navigateMenu(0, 9, &printRomSize_MD);

**Comment by sanni** [comment]
Should be fixed now.

**Comment by PsyK0p4T** [comment]
All good ! thanks for the fast fix
