### ISSUE TITLE
Unable to get save from Star Tropics

### ISSUE THREAD

**Issue by plicease** [sanni/cartreader#1041]
### OSCR firmware version

V14.3

### OSCR hardware version

HW5 Rev1

### Attach OSCR_LOG.txt file here

OSCR HW5 V14.3

[+] NES/Famicom

Searching database
for 508033DC or 2F5D7433...

NES CART READER

CURRENT SETTINGS

MAPPER:   4
PRG SIZE: 256K
CHR SIZE: 256K
RAM SIZE: 1K

Press Button...

[+] Read iNES Rom

Saving to NES/ROM/StarTropics/28/...
[*******************]
CRC32... 889129CB -> StarTropics (USA).nes

Press Button...

[+] Read Save

RAM SIZE 0K

Press Button...

[+] Read Save

RAM SIZE 0K

Press Button...

### System used

NES/Famicom/Family Basic

### Describe the issue.

I've been able to successfully get the save from other battery backup games, and to dump the ROM for Star Tropics, but when I try to get the save I get a message "RAM SIZE 0k". I did verify that the cartridge and saves from way back in the day are working on a real life Nintendo, so the battery is not dead.

I'm not sure which revision of HW5 that I have but can update ticket if I figure it out.  I did purchase premade OSCR from etsy fairly recently.

**Comment by nsx0r** [comment]
Hi, this has been fixed with the latest version, I just checked with my StarTropics cartridge.
