### ISSUE TITLE
Gerber files

### ISSUE THREAD

**Issue by AireagoirSteam** [sanni/cartreader#13]
Are there Gerber files for the all in one variant? The wiki lists ones for another variant.

**Comment by sanni** [comment]
The currently uploaded "github version" pcb design has been tested many times and works great.     
The all-in-one variant is still in development and therefore no gerber files are available.     
Both variants are functionally equivalent so you're not missing out on anything if you order the github version.        

If you really really want the all-in-one then I can send you a prototype pcb, just the pcb no parts.   
Message me on the Arduino forum in case you're interested.
