### ISSUE TITLE
Old version schematic

### ISSUE THREAD

**Issue by glooff** [sanni/cartreader#17]
hi sanni , I really enjoy your project and all the informations you send us . 

I order the component forbthe older version , without GBA option , but I don't find the information of it again ... 

could you please let it again ? I mean the PCB mounting and BOM 

thanks for your feedback 
regards

**Comment by sanni** [comment]
Build guide old version:  https://github.com/sanni/cartreader/wiki/PCB-Build-guide
Parts: https://github.com/sanni/cartreader/wiki/Needed-Parts/26d82ed870367b93ec197ab153b63f9f27a8f25f
User Guide: https://github.com/sanni/cartreader/wiki/Setup-and-user-guide
Overview: https://github.com/sanni/cartreader/wiki/Cart-Reader-SNES-and-N64

**Comment by glooff** [comment]
Thanks for your quick feedback ! 
Last question , concerning the save file , fla , epp and other , can we used directly the file to project 64 emulator or other , or it needs a conversion ? 
I try to used the saves extracted from retrode 2 , but It doesn't work directly ... 

Did you already get this king of problems ? 
thanks 
regards 
laurent

**Comment by sanni** [comment]
Emulators swap the save files around for some reason, so you need to convert the save first using this tool: https://github.com/sanni/cartreader/tree/master/extras/saveswap

**Comment by glooff** [comment]
Many thanks for your help ! it works ! 
The only game it have some difficulties is majoras mask .. 
The rest is ok . 

thanks again !
