### ISSUE TITLE
Where to buy the completed shield?

### ISSUE THREAD

**Issue by greysondn** [sanni/cartreader#30]
Eight months ago you were asked in #14 where a pre-built card reader was and closed it. There was no comment answering it.

So I'll ask here, again: Is there some place I can get ahold of the shield preassembled?

If there is no assembly process in place, where would you recommend handing the gerbers off that would be likely to assemble it for me at a reasonable price? Looking at full assembly, components included.

I'm not looking at going into production - just have a few saves on a few carts I'd like to snag off before the battery dies, even if all I do is pull them off, replace the battery, and write them back to the cartridges. So probably looking at maybe 1-3 of them being ordered, tops.

**Comment by sanni** [comment]
I can sell you one of my test units if you like. Just write me a message on the Arduino Forum (username: sanni) or on Reddit (username: s4nni).
