### ISSUE TITLE
Xplorer64 not read.

### ISSUE THREAD

**Issue by Nes-player4Life** [sanni/cartreader#360]
Cheat devices, Xplorer64 (Xploder64) not read.

**Comment by sanni** [comment]
What happens if you try to dump it?

**Comment by Nes-player4Life** [comment]
Dumps an empty file. GPERROR. Thousands of lines of 0

**Comment by sanni** [comment]
Can you make a picture of the Xplorer64 PCB (front and back)?

**Comment by Nes-player4Life** [comment]
![20210721_140800](https://user-images.githubusercontent.com/10325597/166129636-43ee6546-4d86-4110-8f12-44f6649bd2bb.jpg)
![20210721_140823](https://user-images.githubusercontent.com/10325597/166129638-20831a1f-77bd-4f38-99d9-aecca4dca5cd.jpg)
![20210721_141212](https://user-images.githubusercontent.com/10325597/166129639-471f3b3d-6c51-4fbb-95a8-1302bc050b25.jpg)
![20210721_141241](https://user-images.githubusercontent.com/10325597/166129641-a782c92e-d45a-465c-b040-8ea6b5ed7641.jpg)
![20210721_140850](https://user-images.githubusercontent.com/10325597/166129643-0248d6c6-1188-4d77-89d6-1bad974bbae4.jpg)
![20210721_140909](https://user-images.githubusercontent.com/10325597/166129646-d899d5a8-cc6e-4d5b-ab77-5387cab56bb2.jpg)

As you see some of the chips look like the gameshark chips.

**Comment by sanni** [comment]
Maybe do a complete 64MB dump and then search for Xplorer64 in the file using a hex editor to locate where the bios starts. For example with the Gameshark the bios gets read starting from offset 0xC00000. It could be similar with the Xplorer64.

**Comment by majorpbx** [comment]
I just got one of these carts and it did not dump as well. I haven't had time to troubleshoot but will see if I can get it to work.

**Comment by majorpbx** [comment]
As as side note, I have successfully dumped GameShark v1.05-3.3, Pro & Action Replay versions, Passport & Plus verisons, and Equalizer. These all have the same if not similar ROM chips.

**Comment by Nes-player4Life** [comment]
You dumped the passport with this device? Very cool. And the 1.0.5 gs that is a very early version sweet!

**Comment by majorpbx** [comment]
I did. I cleaned Xplorer64 and it did not dump ☹️ and tried Super Mario 64 (USA) cart and got a blank dump with random data in it.

I also have a Game Killer to dump but this uses a completely new single chip. Uses a PIC16C558-04/S0 chip and looks to be much simpler logic board. I'm guessing for this Game Killer it might need a new method for dumping.

**Comment by Nes-player4Life** [comment]
What version of xplorer64 do you have? I have the orange .0.6. E  i think it is.

**Comment by majorpbx** [comment]
My version info is below. Press and hold Z and you should get something maybe?

Xplorer N64 Version
(C) 1997/9 FCD Release 1.000E
England

Build 1834
Compiled:
Mon Aug 15 12:10:59 BST 1999
