### ISSUE TITLE
Pocket SNES Cart RW - Clock generator not working!

### ISSUE THREAD

**Issue by Hanzel1985** [sanni/cartreader#378]
for some reason, with the new update, i can enable the adafruit clock generator, even if i configure in the main option part in the arduino programmer, can someone help¡

**Comment by sanni** [comment]
Check that the SDA and SCL pins of the Clock Generator are connected to the Arduino.
The newer Cart Reader versions check if the Clock Gen is actually working and print and error if it doesn't.

**Comment by Hanzel1985** [comment]
thanks for the reply sanni!, i see, but where i need to connect those pins??, im using the snes pocket cart rw that uses the arduino mega 2560 pro,

**Comment by sanni** [comment]
I don't know how the Pocket SNES Cart RW is wired as it is not my design. Can you make a picture how the Clock Generator is connected?
