### ISSUE TITLE
5V works, 3.3V does not

### ISSUE THREAD

**Issue by sanni** [sanni/cartreader#379]
### As discussed in https://github.com/sanni/cartreader/discussions/369

There seems to be a new Mega 2560 Pro variant that does not turn on when the Cart Reader is switched to 3V.   

# Update 2:      
This method now has been confirmed to work with HW5 too. You just need to take 3.3V from another point on the PCB since the Cartridge Port Adapter pin header doesn't carry 3.3V with HW5 anymore.

HW5 Rev3: Close solder jumper TP3/TP4

![hw5rev3](https://user-images.githubusercontent.com/19169494/176497144-d2c0041d-8a05-4a90-b2e4-edf433a92e08.jpg)

HW5 Rev2: Connect 3V from voltage switch on right side to 3V of Arduino

![hw5rev2](https://user-images.githubusercontent.com/19169494/176496733-a82ce912-368c-4435-af91-c5e414f22b2d.jpg)

HW5 Rev1: Connect 3V from voltage switch on left side to 3V of Arduino

![hw5rev1](https://user-images.githubusercontent.com/19169494/176496728-5f3c6572-076c-4134-b648-b65f255d0cd1.jpg)

Reminder: This is only needed if your Mega 2560 Pro has the "new PCB design" that does not turn on with the switch set to 3.3V.
Why this works is unknown so far. According to the schematics the 3.3V pin of the Arduino does not power anything so it should not be needed. 

# Update 1:      
A first clue has been found as to what could be causing the issue (HW4):

[0xyzzyx wrote](https://github.com/sanni/cartreader/discussions/369#discussioncomment-3005485):
> So my more permanent solution ended up being soldering a wire to the 3V pin for the arduino to the 3V pin of the cartridge slot on. It's a crude solution but it seems to be working for both 5V and 3V modes without any manual intervention.
> 
> ![main_pcb_solder](https://user-images.githubusercontent.com/76545403/175136117-240578d1-9132-41bd-a937-543481d4c6f1.jpg)
> 
> This shows which two pins I wired together, but I did it on the underside of the board.
> 
> ![cartreader_underside_wire](https://user-images.githubusercontent.com/76545403/175136523-8cdbb41a-5196-4ccd-a6e1-7698bdf3f3d0.jpg)
> 
> Working perfectly now. Will update if this ends up frying my board.

**Comment by sanni** [comment]
It seems that newer Arduino Mega Pro's can't be run at 3.3V anymore. I have ordered one and will have a look as to why.

**Comment by sanni** [comment]
A first clue has been found as to what could be causing the issue:

[0xyzzyx wrote](https://github.com/sanni/cartreader/discussions/369#discussioncomment-3005485):
> So my more permanent solution ended up being soldering a wire to the 3V pin for the arduino to the 3V pin of the cartridge slot on. It's a crude solution but it seems to be working for both 5V and 3V modes without any manual intervention.
> 
> ![main_pcb_solder](https://user-images.githubusercontent.com/76545403/175136117-240578d1-9132-41bd-a937-543481d4c6f1.jpg)
> 
> This shows which two pins I wired together, but I did it on the underside of the board.
> 
> ![cartreader_underside_wire](https://user-images.githubusercontent.com/76545403/175136523-8cdbb41a-5196-4ccd-a6e1-7698bdf3f3d0.jpg)
> 
> Working perfectly now. Will update if this ends up frying my board.

**Comment by stewartspicer** [comment]
Hey there,

I'm having a similar issue, and I'd just like to try to verify that it's the SAME issue before I attempt the same fix.

I'm just now starting to build my reader. The only parts I have installed on the main PCB are the battery holder and the GBA reader board (with slot, headers, and switch).

5v mode, works fine. Same voltage as the 5v out on the battery. 3v mode, I get nada. Looking at the traces, I also fail to see how the power gets from the battery mount to the 3V pin there. I've read through the schematics and followed the traces, but I don't see how the 3.3V actually gets to the 3V pin

**Comment by stewartspicer** [comment]
I think I'm an idjit and the power comes from the screen. Identified the voltage regulator on the LCD module, and it looks like it has a 3.3V output. I just assumed it was input, but I think I'm just gonna send it and try the above fix if I don't have voltage after the screen in installed
