### ISSUE TITLE
Clockgen Not Found - HW Version 3

### ISSUE THREAD

**Issue by Lurick73** [sanni/cartreader#462]
After updating the cart reader from 9.1 to 9.4 I noticed that when trying to pull games it keeps giving a clockgen not installed/found error. Upon looking it seems in 9.1 the following was defined:
#if (defined(HW2) || defined(HW3))
#define enable_OLED
#define enable_Button2
//#define clockgen_installed
//#define fastcrc
#endif

But in 9.4 it changed to:
#if (defined(HW2) || defined(HW3))
#define enable_OLED
#define enable_Button2
#define clockgen_installed
//#define fastcrc
#endif

Which I suspect is triggering the error. Commenting clockgen_installed out and uploading again does fix the error.

**Comment by sanni** [comment]
Thanks for reporting, I have now updated the "How to flash the Arduino" Wiki article to include a section about the "#define clockgen_installed" option.
