### ISSUE TITLE
Auto naming files

### ISSUE THREAD

**Issue by Icesythe7** [sanni/cartreader#467]
currently on version 9.4, it will auto name your dumps and then if you try to flash them it cant display the file as the name has characters that it can't print or are too long(idk the issue) manually renaming the file fixes the issue.

To reproduce dump pokemon blue, then try to write it to a flashcart and it doesn't exist as an option until you manually rename the file.

**Comment by sanni** [comment]
Either I'm using the Sdfat function getName() not correctly or the library has a bug.

![getName](https://user-images.githubusercontent.com/19169494/185614221-1b71b6fe-ad6d-43f1-aa6d-e6a39e108f60.jpg)

![truncate_error](https://user-images.githubusercontent.com/19169494/185613730-29214fa7-2f19-4424-b221-af0faa82c6af.jpg)

[Arduino Sketch Download](https://github.com/sanni/cartreader/files/9381907/truncate_error.zip)

**Comment by sanni** [comment]
Must be a bug in SdFat library. Truncating works in 2.1.1 as expected but not in 2.1.2 or 2.2.0
https://github.com/greiman/SdFat/releases

**Comment by sanni** [comment]
Should be fixed with V9.5_Portable by increasing file name length limit and reverting to SdFat library 2.1.1.
