### ISSUE TITLE
Phantasy Star IV dumps with checksum error

### ISSUE THREAD

**Issue by sanni** [sanni/cartreader#487]
### Discussed in https://github.com/sanni/cartreader/discussions/399

<div type='discussions-op-text'>

<sup>Originally posted by **ryaneallen3** July  6, 2022</sup>
Dumped Phantasy Star IV and got a checksum error. Tried loading it in BizHawk and I see the Sega logo and music before it freezes. I tried the FixCheckSum tool, as that worked for me to get Beyond Oasis dump to work, but PSIV does the same thing after checksum fix. How can I dump?</div>

**Comment by sanni** [comment]
Fixed by disabling SRAM before dumping

**Comment by flyingclimber** [comment]
This fixed it for me. Thank you!
