### ISSUE TITLE
PC Engine rename error

### ISSUE THREAD

**Issue by Nanths** [sanni/cartreader#540]
Hi!

I was dumping several hucard with a custom adapter and noticed the name of files doubled the extension, as you can see below:

![pcengine_names](https://user-images.githubusercontent.com/96782274/193100156-37db1885-09dd-4f95-ad1e-0256d7d1aebd.png)

I suppose it is a easy fix into the code.

**Comment by sanni** [comment]
Can you try removing those two lines in pce.ino, this should fix it.

![hgeggagagfaff](https://user-images.githubusercontent.com/19169494/193102126-78202cbf-2c99-4ffe-97cd-ec88d617484e.jpg)

**Comment by Nanths** [comment]
Yes, is fixed now. Thank you. 😃
