### ISSUE TITLE
[NES] changing mapper manually triggers database search again

### ISSUE THREAD

**Issue by PsyK0p4T** [sanni/cartreader#607]
Latest merges in NES.ino brought a little issue (got it with hw3 and today's version) : 
- go into NES module
- the game autodetection starts
- a game is found, mapper settings are set
- I don't want these settings, so go to Changer Mapper
- set new values for PRG, CHR, RAM
- and at this point autodection is launched again. The game is found again. Manual settings are overwritten etc.

This comes from checkStatus_NES(), calling getMapping();

**Comment by sanni** [comment]
Good catch. Try the newest build. 👍

**Comment by PsyK0p4T** [comment]
Confirmed, latest build fixed it :)
