### ISSUE TITLE
[NES] game detection broken in v11.3

### ISSUE THREAD

**Issue by nsx0r** [sanni/cartreader#630]
NES game detection is broken in v11.3

working fine in v10.2 (release zip)
![image](https://user-images.githubusercontent.com/13054953/202639091-e4512260-fa09-49fc-8a26-86bdd9443dc6.png)

broken in v11.3 (present version at commit [8dcb841](https://github.com/sanni/cartreader/commit/8dcb84110968469345c035346fb01963b26ad4fe))
![image](https://user-images.githubusercontent.com/13054953/202639129-3302fd3b-5237-4be2-95e0-ce755808a1cf.png)

edit: I updated the files on SD card too

**Comment by sanni** [comment]
Should be fixed now. 👍

**Comment by nsx0r** [comment]
> Should be fixed now. 👍

it works, thank you!
