### ISSUE TITLE
Problem with downloading V3 .stl files

### ISSUE THREAD

**Issue by luk3ros** [sanni/cartreader#648]
Hello,
I have a problem with downloading .stl files form "Adding an enclosure" section. Same problem have with files in section "3d printed case files". Most cases there is no "download" button.  Can You please fix this or ?
Thank You for Your time.
Lucas

**Comment by sanni** [comment]
https://github.com/sanni/cartreader/archive/a981bb0c3e9143cb1268e77311eadaa620eff621.zip
