### ISSUE TITLE
Unable to read LRG NES cart

### ISSUE THREAD

**Issue by retrovik** [sanni/cartreader#679]
I am unable to read the Limited Run Games SCAT NES cart. It seems to read fine at first (finds the entry in the database), but then gives an error on the CRC check at the end. The file created is not usable. Using HW V3 and Firmware beta V12.0 (I also tried 10.2). I am guessing the fact that this is not an actual mapper 1 board but an FPGA simulation of one is the issue. I am not sure if this is a bug or a feature request. Just FYI.

[SCATSpecialC.txt](https://github.com/sanni/cartreader/files/10394768/SCATSpecialC.txt)

![thumbnail_IMG_5137](https://user-images.githubusercontent.com/122476671/211880434-f965e5ea-e499-454f-a60a-0389a7ec80bc.jpg)

![thumbnail_IMG_5138](https://user-images.githubusercontent.com/122476671/211880449-1f6bbaf9-2efb-406c-b357-96f258513851.jpg)

**Comment by nsx0r** [comment]
Hi, could you join Discord to run some tests? https://discord.gg/YVxv7BnzXt

**Comment by Cephiros** [comment]
Looking at that cart, seems like alot going on for an mmc1 game. I wouldnt be surprised at all if limited run built some anti-dumping code into that FPGA that can detect if its plugged into an actual NES, or if something is just reading and probing the address and data lines.

**Comment by nsx0r** [comment]
I think I have a workaround, come back to Discord ;D

**Comment by retrovik** [comment]
@nsx0r Your workaround worked perfectly. I just had to manually edit the generated header in a hex editor since it was in ascii. After that, it works great now. Thanks!


![scat2](https://user-images.githubusercontent.com/122476671/212574223-ed0afe3f-6da2-4c43-b8f4-ca228926945f.png)


![scat1](https://user-images.githubusercontent.com/122476671/212574230-7c9ba1e4-bc2a-44dd-b00a-e38b1686bb0e.png)

**Comment by nsx0r** [comment]
this issue can now be closed, as it's related to NES 2.0 not supported at the moment https://github.com/sanni/cartreader/issues/442
