### ISSUE TITLE
Old HW3 flashrom adapters do not work with HW4 and HW5

### ISSUE THREAD

**Issue by VitorBR254** [sanni/cartreader#690]
Does not work cart reader v5?

**Comment by sanni** [comment]
No, the old flashrom adapters do not work with HW4/HW5 only with HW2/HW3.

The WE and OE pin on the old flash adapter needs to be cut and rewired to make them work with HW4/HW5.
WE flashrom now goes to SNES WR, before it was SNES IRQ.
OE flashrom now goes to SNES CS, before it was SNES CPU CLOCK.
