### ISSUE TITLE
GB(C): Add support for EEPROM save (Kirby Tilt 'n' Tumble/Koro Koro Kirby)

### ISSUE THREAD

**Issue by PW5190** [sanni/cartreader#717]
Hey there. I recently got my hands on the Open Source Cartridge Reader. I put Kirby Tilt 'n' Tumble into the Game Boy slot, and I was able to dump the ROM. But, when I attempted to backup the save file, I get an error message.

```
Cart has no Sram

Press Button...
```

Any chance this issue can be fixed? I really need to backup my save file. As far to my knowledge, this is one of the few Game Boy (Color) games to not use battery-backed SRAM for saving, and instead utilizing EEPROM. And this is one of two Game Boy Color games to have a tilt sensor. The other game that has it is Enix's Command Master.

Trust me, I followed the guide on the PCB. Made sure the voltage switch was in 5V, and the EEP, CLK0, and CLK1 switches are off. Do I also need to turn the EEP switch on, since the cart used EEPROM?

**Comment by sanni** [comment]
There currently is no code to read/write eeprom in GB.ino.
If you wanna give it a try yourself here is the needed information about the eeprom: https://gbdev.gg8.se/wiki/articles/MBC7#Ax8x_-_EEPROM_.28Read.2FWrite.29
