### ISSUE TITLE
screen does not display correctlly when in 3v mode

### ISSUE THREAD

**Issue by machineh3d** [sanni/cartreader#735]
this is my first project like this and i thought everything was going fine i was able to dump some GB carts and SNES carts 

but the moment i try and turn it on with the switch set to 3v the screen either looks glitchy or nothing at all 

5V
![fine](https://user-images.githubusercontent.com/11908515/224516130-cd5d8be0-3094-48fa-96ce-0c9c9d068894.jpg)

3v
![20230311_151447](https://user-images.githubusercontent.com/11908515/224516142-8287530e-778e-4789-9e78-99d7845be042.jpg)

**Comment by djbiohazard** [comment]
Mine is being weird too, It's fine at 5V setting, but once I switch it to 3V setting, it'll boot, briefly show a message, before showing a green solid screen.

**Comment by machineh3d** [comment]
> Mine is being weird too, It's fine at 5V setting, but once I switch it to 3V setting, it'll boot, briefly show a message, before showing a green solid screen.

I fixed mine by replacing the MEGA 2560 pro with a new one. The one that wasn't working was a ATMEGA2560-16AU and I swapped it with ATMEGA256016U2 and now it works with 5v and 3.3v no problems at all

**Comment by Ancyker** [comment]
You might be shorting 5V to VCC. The 3.3V comes from the LCD.

**Comment by djbiohazard** [comment]
@Ancyker Problem is solved. 

My ADD brain caused me to desolder the diode instead of the fuse. 
Ofc the diode was long gone. Replaced it with 1N4148, and it's now working fine.  Did (eventually) remove the fuse.
