### ISSUE TITLE
Order list mistake?

### ISSUE THREAD

**Issue by BenoitCaron** [sanni/cartreader#741]
I recently purchased all the items on the list, assembled my cart reader, and realized those long male pin headers are actually too long?

```
Male pin headers:
two 1x40 2.54mm 20mm long(total length) 
```

The PCB can't sit flush with the 18mm spacers, because male pin headers + female pin header combined are 18.5mm. I triple checked, I did order according to the list, my male pin headers are indeed 20mm long.

At that point, I would advise either to change the list to 19mm long spacers, or 19mm long male pin headers :) 

![IMG_0078](https://user-images.githubusercontent.com/5237965/226973170-d27e777b-d12d-4d39-be3f-8e7663a77c5b.jpg)

![IMG_0079](https://user-images.githubusercontent.com/5237965/226973157-ab382e3a-49f7-4936-8ba3-22c6d4835cf5.jpg)

**Comment by Ancyker** [comment]
![image](https://user-images.githubusercontent.com/7105333/226983336-ae91629f-a08e-4413-9cfe-75be65be92a3.png)

**Comment by Ancyker** [comment]
Mine is like that too, I just screwed it down anyway 🤷‍♀️

**Comment by Ancyker** [comment]
I think it's fine, but I also didn't wrench them down super tight; I just made them snug on both sides; there's still a tiny gap.

**Comment by Ancyker** [comment]
@sanni  I checked a few, and with the variance, I think increasing it more might lead to being too short at 19mm. I don't think that will affect usage, but I'm not sure. Since washers are on the list, anyone concerned could just add washers between the PCB and standoffs...

**Comment by BenoitCaron** [comment]
Huh, that's strange, I had the feeling that it could be shortened even more, like 18mm pins wouldn't be an issue :o

**Comment by Ancyker** [comment]
If you are super concerned, you can just put a washer between the top PCB and standoff. I just didn't tighten them all the way, but if you are worried about it, then it's an option. If you bought everything on the list, you likely have a huge pack of washers sitting around doing nothing anyway, lol.

**Comment by BenoitCaron** [comment]
Maybe we misunderstand each other. My only concern is the flex. I'm not concerned about shortening the pins (which I did) nor using washers. I'm designing a shell that I might release. If people use my shell, I'll need them to have the exact same height as I do, and the more reliable way to have the same height, in my opinion, is to use shorter pins, as different washer might vary in height. Either way, both solutions are perfectly valid I think :)

**Comment by Ancyker** [comment]
The washers are nice because of the material they are made of they do compress a little unlike metal. This means you can get a pretty reliable height out of them. None of these things are super high tolerance, though. These are cheap parts from China. I'd expect a 0.1-1mm variance on both the standoffs and headers. Hell, I've accidentally pushed the header pins through their plastic holder.

1-2mm shouldn't affect your housing as long as you design it for the max height/worst case, as either way, the cutouts for the slots need to allow the entire cart to pass through. You shouldn't design it so that the housing is touching the PCB. There's a reason no consoles (that I know of, at least) do that. Even the GBA isn't completely flush.

**Comment by BenoitCaron** [comment]
You have a point.

**Comment by Ancyker** [comment]
Also, what is your housing doing differently? There's already a full-enclosure available if that's what you wanted.

I'd like to see one for SLA, as I don't have an FDM printer, and I'll be getting an SLA printer soon. But resin doesn't melt; it burns, so it will need a different design for mounting the LCD.

**Comment by BenoitCaron** [comment]
My printer's bed is 150mm long, so I can't print the ones that I have found so far, which are a tad too long. Plus, I'm often not satisfied with the models I find, and try to make my own both as practice and to get better results than current offerings :)

**Comment by Ancyker** [comment]
Ah, that's fair. The one someone posted a few weeks ago (#723) is a bit larger @ ~162mm. The printer I'm looking at is 250x123x219mm (HWD, supposedly, but I'm pretty sure they meant WDH, though I'm not totally sure). 

The OSCR has seemed a bit chunky looking when it has fully enclosed housing on it. I'm interested in seeing what you come up with. ☺

**Comment by Ancyker** [comment]
I saw a cart reader with this housing on eBay:

![image](https://user-images.githubusercontent.com/7105333/227017189-9d2f26a8-f507-4457-9891-a4bffb03ad2c.png)
![image](https://user-images.githubusercontent.com/7105333/227017249-01dcadb7-0b14-4117-872b-8de3828e872f.png)

It looks smaller like it would fit on your printer, but as far as I know, the creator did not make the files available. Still, could be used for inspiration, perhaps.

**Comment by BenoitCaron** [comment]
Yep, this one would most definitely fit ! But I'm almost done, so I don't think I will draw much inspiration from it :/
At first glance I though "oh the 3V and 5V labels are a smart addition", but then remembered that the software actually tells you which cartridges are 3V.
Thanks for sharing this!

**Comment by Ancyker** [comment]
Yeah, I'm pretty sure that was listed/created before the software said that. Also, if you use Vselect, you don't even have a voltage switch, lol.

I put my N64 controller port in a different place as well.

**Comment by BenoitCaron** [comment]
I wanted to put it in the back near the GBA port, on the site. I was almost perfect, but ultimately just too tight.

**Comment by Ancyker** [comment]
I put mine on the side under the six-slot, lol.

![2022-12-20 13 01 24](https://user-images.githubusercontent.com/7105333/227044026-8496c0c6-07e8-48f6-b691-af23aca0b33f.jpg)

Also, now that you mentioned the flex, I can't unsee it 😅

**Comment by BenoitCaron** [comment]
Yeah that's exactly what I wanted to do, but on the opposite side ;)
Hope you still have those spacers somewhere :D
