### ISSUE TITLE
Atari - Scrolling backwards shows bad text

### ISSUE THREAD

**Issue by PsychoFox11** [sanni/cartreader#793]
Using my Atari adapter for the first time, and noticed when scrolling through the game list, if you scroll backward through the titles, it shows either the end of the game name or a seemingly random number. Scrolling forward again shows the game titles correctly.

**Comment by sanni** [comment]
Some of the database files in the 12.4 release were broken(LF instead of CRLF line ending). Please update to the latest databases and try again.
