### ISSUE TITLE
[Minor][N64][UI] Game title not displayed correctly

### ISSUE THREAD

**Issue by ezcGman** [sanni/cartreader#806]
Hey there,

I was trying to dump my European copy of Extreme-G and I recognized that the title is not displayed correctly:
![1686046697524](https://github.com/sanni/cartreader/assets/3090131/05ed1f7d-0834-4a2a-896a-cf64511dac78)
I validated that the 2nd CRC (8E9D834E) it finds actually is in the [N64 database](https://github.com/sanni/cartreader/blob/master/sd/n64.txt#LL692C1-L692C18) and it is indeed Extreme-G (EUR).

However, when you dump the ROM and it does the CRC check showing the first CRC (0B71B1EA), it actually displays the title correctly:
![1686046893412](https://github.com/sanni/cartreader/assets/3090131/39e1b9c2-92b3-478b-96f9-c0562a5d5d99)

So I guess it is just a display issue?

Let me know if you need more info!

Greetings,

Andy!

**Comment by PsyK0p4T** [comment]
The "Title" string displayed on first line is just the ROM internal name, as it was coded in the ROM header. There is no check or format operation for it.

"CRC1" is a header checksum. Used to identify the game and its size.
"CRC32" is the global checksum for the rom file. If it matches a db entry, then the rom is renamed.

Everything's looking fine here.
