### ISSUE TITLE
Checksum matched on bad dumps of GBA game

### ISSUE THREAD

**Issue by muellerm1** [sanni/cartreader#81]
I dumped a Mother 3 GBA cartridge to apply the fan translation patch, but got an error. The ROM was incorrect. So I dumped it three times and checked the MD5 hashes of each. All different. One of them was actually correct, and was accepted by the translation patch. The other two were not.

**The cart reader said the checksum matched on all three of those dumps.** This makes me wonder if my other games were also dumped incorrectly.

**Comment by sanni** [comment]
The GBA code is still very buggy. You can try to clean the carts contacts with rubbing alcohol and a q-tip, maybe it helps.
The internal ROM checksums of Nintendo games are only calculated from a small portion of the ROM and do not actually tell whether or not a dump was successful. 
You can use a a ROM manager on your PC together with the no-intro DAT file to check all your dumps.
