### ISSUE TITLE
Famicom: Unable to dump save file from Mother

### ISSUE THREAD

**Issue by JoshuaRamey** [sanni/cartreader#826]
As the title says, I seem to be unable to dump my save file from this game. If I try dumping the save then the only text that displays is "push button", but if I dump the rom first then it looks like it dumps the save however it isn't there when I check the SD card.
![IMG_1909](https://github.com/sanni/cartreader/assets/46817406/8ac25365-436f-4fab-9eb0-876d2a652e7d)

**Comment by sanni** [comment]
Can you try [updating](https://github.com/sanni/cartreader/wiki/Troubleshooting#updating-to-the-latest-github-code) to the current development code and try again, there was a bug in V12.4. The save should be called ram##.bin

**Comment by JoshuaRamey** [comment]
Thanks. I'm away from home for the next few days but I'll give it a try when I get back.

**Comment by JoshuaRamey** [comment]
Thank you for the help. I was able to dump my save using the latest release.

![IMG_2093](https://github.com/sanni/cartreader/assets/46817406/efea1871-2ad8-4e5a-b17d-abf1827aac12)
