### ISSUE TITLE
CRC32 not found for MD/Genesis NHL 98

### ISSUE THREAD

**Issue by LucidusMC** [sanni/cartreader#841]
### OSCR firmware version

12.4

### OSCR hardware version

HW3

### Attach OSCR_LOG.txt file here

[OSCR_LOG.txt](https://github.com/sanni/cartreader/files/12423831/OSCR_LOG.txt)
![image](https://github.com/sanni/cartreader/assets/45952432/e958b537-4e3d-4b26-824a-9a26f8613edc)
![NHL98 Back PCB](https://github.com/sanni/cartreader/assets/45952432/6826a170-efa2-456c-a2ad-e340b700dad1)
![NHL98 Front PCB](https://github.com/sanni/cartreader/assets/45952432/666dae9d-374f-450f-87b3-9a609868fbbb)

### System used

Sega Mega Drive/Genesis

### Describe the issue.

Trying to dump MD/Genesis NHL 98 on HW3 with 12.4. (See attached) and getting not found and I can't seem to run the bin file as it is written. I have also attached pictures of the PCB. I have successfully played the game on my console (I know this doesn't always mean the cartridge is stable) and cleaned the contacts thoroughly.

OSCR HW3 V12.4

[+] About

Cartridge Reader
github.com/sanni
2023 Version 12.4

Press Button...

OSCR HW3 V12.4

[+] Mega Drive/Genesis

[+] Game Cartridge

Cart Info
 
Name: NHL98
Size: 4 MBit
ChkS: 5B3A
Sram: 256 KBit
 
Press Button...

[+] Read Rom

Saving to MD/ROM/NHL98/31/...
[*******************]
Internal checksum...OK
CRC32... 5CB4A9AD -> Not found
Press Button...

**Comment by Ancyker** [comment]
Is the CRC the same every time you dump it?

**Comment by LucidusMC** [comment]
> Is the CRC the same every time you dump it?

Yes

**Comment by Ancyker** [comment]
Are you in the Discord?

**Comment by LucidusMC** [comment]
Yes. Just joined.
