### ISSUE TITLE
Transfer Pak support?

### ISSUE THREAD

**Issue by upintheairsheep** [sanni/cartreader#952]
### OSCR firmware version

N/A

### OSCR hardware version

HW5 Rev6

### System used

all/none/doesn't matter

### Describe the issue.

The Nintendo 64 Controller ports should include support for dumping the GB/GBC ROMs from a Nintendo 64 Controller’s transfer pak, if one would prefer to dump it from there, to dump two carts at once, or the GB series reader is broken.

**Comment by Ancyker** [comment]
It's possible but I don't see much benefit in it. The GBA slot is on the main PCB, so you'd already have it. It would increase the PROGMEM usage too. Also, it would only support GB/GBC. Finally, even on the N64 the Transfer Pak was temperamental and would corrupt saves and stuff sometimes.
