### ISSUE TITLE
purpose of snes.ino "boolean altconf"?

### ISSUE THREAD

**Issue by smesgr9000** [sanni/cartreader#973]
### OSCR firmware version

V13.3

### OSCR hardware version

HW5 Rev6

### System used

SNES/Super Famicom

### Describe the issue.

What is the purpose of the flag "altconf" in snes.ino?
It seems it only toggles print lines between those variants:
"Rom Size: "
"ROM Size: "

It would like to remove this flag if it hasn't any other purpose.

**Comment by sanni** [comment]
I remember I created that variable to signal that the rom header of the SNES cartridge was wrong and instead the config from the snes.txt database was used. 
````
"Rom Size: "
"ROM Size: "
````
was an indicator that this happened before I added the log file where you can now easily read that it got changed.

So yeah, you can remove it as it doesn't have a purpose anymore.

**Comment by smesgr9000** [comment]
thanks for the explanation
