### ISSUE TITLE
U1 is missing on the Schematic

### ISSUE THREAD

**Issue by Helder1981** [sanni/cartreader#986]
### OSCR firmware version

N/A

### OSCR hardware version

HW5 Rev6

### System used

all/none/doesn't matter

### Describe the issue.

The PCB file has the U1 part but on the schematic it is not there, can this be fixed?

**Comment by Helder1981** [comment]
Sorry I am new to kicad and did not know how to go to sheet 2 that has the U1 there.

**Comment by Ancyker** [comment]
Yeah, if you click VSELECT on the main schematic it will open it. There should also be a nav bar on the left I believe. The next revision actually has 5 pages total :3

![image](https://github.com/user-attachments/assets/008aaeb4-032d-4a40-8e6f-d13a5adaac6d)

**Comment by Helder1981** [comment]
It was the V-Select IC. I'm adding the clock generator to the main pcb and maybe the n64 controller port and Super CIC. Planning to just have the cart pcb the 7in1 to just have cart slots.

**Comment by Helder1981** [comment]
Ah nice , I've been wanting to include the Mega since I first learned of this project. What are the FFC sockets for?

**Comment by Ancyker** [comment]
To connect to the new top PCB which also includes a header for the RetroSix GG slot.
