### ISSUE TITLE
All Configurations via Menu 

### ISSUE THREAD

**Issue by StanMOI** [sanni/cartreader#992]
### OSCR firmware version

14

### OSCR hardware version

HW5 Rev6

### System used

all/none/doesn't matter

### Describe the issue.

Hello Sanni,

I think it's will be great to have "Configuration" option into MENU, 
so we can configure (ENABLE / DISABLE) all basic stuffs like:

- HARDWARE VERSION
- HARDWARE MODULES
- GAME SYSTEM CORES
- Flashrom Programmer for repro carts...

It's also will be great if once when it configured, it's stored somewhere on SD card, so when we do "Arduino" code update we not need to re-configure it again and agin.

**Comment by sanni** [comment]
The Mega2560 does not have enough space for this. All deactivated modules do not get flashed to the Mega2560. 
Maybe a future hardware revision with a modern microcontroller can do this.
